### ISSUE TITLE
Pathname::glob is not always available

### ISSUE THREAD

**Issue by ssendev** [kenn/age_calculator#2]
I upgraded a rails 5.0 application to 5.1 and lots of other gems so i'm not sure who the culprit ist but it caused rails to fail to start since Pathname::glob was not available.

One solution would be to depend on https://github.com/taw/pathname-glob but i think it should be enough to just add the folder and not the individual files or hardcode them since it is only one.

**Comment by bdezonia** [comment]
I am wondering if this was just introduced by the change allowing asof: dates for age calculation. It seems that this code changed in lib/age_calculator/railtie.rb during that update:


(REMOVED)      locale_path = Dir.glob(File.expand_path('../../../config/locales/*.yml', __FILE__))
(REMOVED)      I18n.load_path += locale_path unless I18n.load_path.include?(locale_path)
(ADDED)      I18n.load_path += Pathname.new(__FILE__).dirname.parent.parent.glob('config/locales/*.yml')

Now when I launch rails I get this complaint:

/Users/bdezonia/.rvm/gems/ruby-2.3.6@reggie_rails/gems/age_calculator-1.2.0/lib/age_calculator/railtie.rb:6:in `block in <class:Railtie>': undefined method `glob' for #<Pathname:0x00007fecea49e1a0> (NoMethodError)

**Comment by kenn** [comment]
Fixed with v1.2.1 - I'd appreciate if you could confirm the fix works for you!

**Comment by ssendev** [comment]
Yes it works. Thanks for the quick response.
