### ISSUE TITLE
Broken for leap years

### ISSUE THREAD

**Issue by jtwhittington** [kenn/age_calculator#4]
This will return wrong dates for leap years. Say someone was born on 1984-02-29 and it is the 28th of February on a non-leap year, e.g. 2019, they should be 35 (this gem will return 34). 

Just FYI - was thinking about using this gem but it failed my tests.

**Comment by kenn** [comment]
Is there a standard that defines what your age should be when you're born on Feb 29th? I'm not familiar with it.

**Comment by jtwhittington** [comment]
Hmm, don't think it is as easy as that after digging into it more. Apparently it switches legally between countries on whether Feb 28th or March 1st is considered their birthday. 

So I guess the current way is fine and would depend on requirements of users. Maybe should just document how it is handled?

**Comment by kenn** [comment]
OK, thanks for your research. I think it's ok as it is because it's intuitive enough, and it's a super corner case for the typical use case - a person born in leap year happens to visit the website on their birthday. I'm closing this now, but feel free to make a pull request for documentation.
